services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-paper_insight}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paper_insight_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - paper_insight_net

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - postgres
    networks:
      - paper_insight_net

  celery_worker:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - postgres
    command: celery -A celery_worker.celery_app worker --loglevel=info
    networks:
      - paper_insight_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - paper_insight_net

volumes:
  postgres_data:

networks:
  paper_insight_net:
    driver: bridge 