version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    depends_on:
      - redis
    command: celery -A celery_worker.celery_app worker --loglevel=info

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev 